# 서버 포트 설정
server:
  port: 8084

# oauth yml include
spring:
  config:
    import: "classpath:application-jwt.yml"
  profiles:
    active: "oauth"


# DB 접속 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: '1234'

# jpa hibernte 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create